---
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    remote_user: usuario
    become: true
    become_user: root

- hosts: all
  name: Collect facts
  tasks: [ ]
  remote_user: usuario
  become: true
  become_user: root

  roles:
      - remote_exec1
