---
# tasks file for remote_exec1

- name: check sudo group exists
  group:
    name: sudo
    state: present
    gid: 27

- name: Add the user 'emergya' with a bash shell and sudo group
  user:
    name:  emergya
    state: present
    shell: /bin/bash
    createhome: yes
    groups: 'sudo'
    append: yes

# #https://docs.ansible.com/ansible/latest/modules/file_module.html#file-module
# - name: Create user home directory
#   file:
#     path: /home/emergya
#     state: directory
#     owner: emergya
#     mode: 0775

# #https://docs.ansible.com/ansible/latest/modules/synchronize_module.html
# - name: Synchronization with --archive mode
#   synchronize:
#     src: /etc/skel/
#     dest: /home/emergya/
#     archive: yes

- name: Create ssh user directory
  file:
    path: /home/emergya/.ssh
    state: directory
    owner: emergya
    group: emergya
    mode: 0700

- name: get file names to copy
  command: "find /home/ubuntu/.ssh -type f"
  register: files_to_copy

- name: copy files
  copy:
    src: "{{ item }}"
    dest: "/hoome/emergya"
    owner: emergya
    group: emergya
    remote_src: True
    #mode: 0644
  with_items:
   - "{{ files_to_copy.stdout_lines }}"

#- name: Copying ssh home directory
  # "Remote copy does not support recursive copy of directory"
  # copy:
  #   src: /home/ubuntu/.ssh
  #   dest: /home/emergya/
  #   owner: emergya
  #   group: emergya
  #   mode: 0600
  #   remote_src: yes
  #-------------------------------
  # "Uses ssh conection with localhost (wtf?)"
  # synchronize:
  #   src: /home/ubuntu/.ssh
  #   dest: /home/emergya
  #   dirs: yes
  # delegate_to: localhost


- name: Create sudoers file
  file:
    path: /etc/sudoers.d/99-ssh-username
    state: touch

- name: Add user to sudoers file
  lineinfile:
    path: /etc/sudoers.d/99-ssh-username
    line: 'emergya ALL=(ALL) NOPASSWD:ALL'
