---
# tasks file for remote_exec1
- name: Add the user 'emergya' with a bash shell and sudo group
  user:
    name:  {{ remote_exec1.ssh_username }}
    state: present
    shell: /bin/bash
    createhome: yes
    groups: sudo
    append: yes

# #https://docs.ansible.com/ansible/latest/modules/file_module.html#file-module
# - name: Create user home directory
#   file:
#     path: /home/{{ remote_exec1.ssh_username }}
#     state: directory
#     owner: {{ remote_exec1.ssh_username }}
#     mode: 0775

# #https://docs.ansible.com/ansible/latest/modules/synchronize_module.html
# - name: Synchronization with --archive mode
#   synchronize:
#     src: /etc/skel/
#     dest: /home/{{ remote_exec1.ssh_username }}/
#     archive: yes

- name: Create ssh user directory
  file:
    path: /home/{{ remote_exec1.ssh_username }}/.ssh
    state: directory
    owner: {{ remote_exec1.ssh_username }}
    group: {{ remote_exec1.ssh_username }}
    mode: 0700

- name: Copying ssh home directory
  copy:
    src: /home/{{ remote_exec1.ssh_default_username }}/.ssh
    dest: /home/{{ remote_exec1.ssh_username }}/
    owner: {{ remote_exec1.ssh_username }}
    group: {{ remote_exec1.ssh_username }}
    mode: 0600

- name: Create sudoers file
  file:
    path: /etc/sudoers.d/99-ssh-username
    state: touch

- name: Add user to sudoers file
  lineinfile:
    path: /etc/sudoers.d/99-ssh-username
    line: '{{ remote_exec1.ssh_username }} ALL=(ALL) NOPASSWD:ALL'
