---
# tasks file for remote_exec2
- name: Create symbolic link for locatime
  file:
    src: "/usr/share/zoneinfo/Europe/Madrid"
    dest: "/etc/localtime"
    state: link

# not necessary
# - name: Change ownership of home directory
#   file:
#     path: /home/emergya
#     owner: emergya
#
- name: Change id_rsa permisions
  file:
    path: /home/emergya/.ssh/id_rsa
    owner: emergya
    mode: 0600
#   ignore_errors: yes

- name: Change id_rsa.pub permisions
  file:
    path: /home/emergya/.ssh/id_rsa.pub
    owner: emergya
    mode: 0644
#   ignore_errors: yes

- name: Execute iptables script
  script: /usr/local/bin/custom-iptables
  ignore_errors: yes #there is no custom-iptables yet

- name: Install requirements
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
     - facter
     - curl
     - git
     - curl
     - expect
     - iptables-persistent
     - nfs-common
     - htop
     - sysstat
     - iotop
     - bwm-ng
     - rsync
     - tcpdump
     - tcpick
     - strace
     - screen
     - inotify-tools
     - socat
     - bash-completion
     - ntp
     - ntpdate
  become: true
  become_user: root

- name: Delete iptables.rules file
  file:
    state: absent
    path: "/etc/iptables/rules.v4"
  become: true
  become_user: root

# check this!!!!
- name: execute command
  shell: sudo iptables-save | sudo tee -a /etc/iptables/rules.v4
  become: true
  become_user: root

- name: Edit ssh config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitRootLogin yes'
    line: 'PermitRootLogin without-password'
  become: true
  become_user: root

- name: Restart ssh service
  service:
    name: sshd
    state: restarted
  become: true
  become_user: root

- name: Download baids repository
  get_url:
    url: https://raw.githubusercontent.com/rcmorano/baids/master/baids
    dest: /tmp/baids
    mode: 0555

- name: Install baids
  command: /tmp/baids install
  #become_user: emergya

- name: Create project directory
  file:
    path: /home/emergya/Projects/emergya
    state: directory
    owner: emergya
    group: emergya
    mode: 0775

- name: Login emergya docker-registry
  get_url:
    url: https://raw.githubusercontent.com/Emergya/docker-registry-expect-scripted-login/master/docker-registry-expect-scripted-login
    dest: /usr/local/bin/docker-registry-expect-scripted-login
    mode: 0775

- name: Clone proyect repository
  git:
    repo: 'git@github.com:Emergya/ebs-corporate-sites.git'
    # repo: 'https://github.com/Emergya/ebs-corporate-sites.git'
    dest: /home/emergya/Projects/emergya/ebs-corporate-sites
    clone: yes
    key_file: /home/emergya/.ssh/id_rsa

- name: Link project baids
  file:
    src: "/home/emergya/Projects/emergya/ebs-corporate-sites/baids"
    dest: "/home/emergya/.baids/functions.d/ebs-corporate-sites"
    state: link

- name: Load projects baids and install docker requisites
  command: /home/emergya/.baids/baids && dev-ebs-corporate-sites.emergyalabs.com-install-env
  #become_user: emergya

- name: Load projects baids and install docker requisites
  command: /home/emergya/.baids/baids && dev-ebs-corporate-sites.emergyalabs.com-install-env
  #become_user: emergya

- name: Docker Registry login
  command: export DOCKER_REGISTRY_URI="{{ docker_registry_uri }}"; export DOCKER_REGISTRY_USER="{{ docker_registry_user }}"; export DOCKER_REGISTRY_PASS="{{ docker_registry_pass }}"; docker-registry-expect-scripted-login

- name: Launch project
  command: source $HOME/.baids/baids; echo y |dev-ebs-corporate-sites.emergyalabs.com-redeploy
